# ------------------------------------------------------------------------------
# --- Definitions, names, lists ------------------------------------------------
# ------------------------------------------------------------------------------

# Spaltennamen der einzelnen Events
names_prefix <- c("uid", "milisec", "eventtype")
col_headers <- list(
  app.heartbeat = names_prefix,
  app.start = names_prefix,
  call.incoming.answered = c(names_prefix,
                             'number',
                             'time_start',
                             'time_answer',
                             'time_end'),
  call.incoming.missed = c(names_prefix,
                           'number',
                           'time_start',
                           'time_answer',
                           'time_end'),
  call.outgoing = c(names_prefix,
                    'number',
                    'time_start',
                    'time_answer',
                    'time_end'),
  device.airplane.off = names_prefix,
  device.airplane.on  = names_prefix,
  device.cell.location = c(names_prefix,
                           'type',
                           'cid',
                           'lac',
                           'operator_numeric'),
  device.cell.service = c(names_prefix,
                          'state',
                          'operator_short',
                          'operator_long',
                          'roaming'),
  device.network = c(names_prefix,
                     'connected',
                     'roaming',
                     'wifi'),
  sensor.gps = c(names_prefix,
                 'time2',
                 'loc_y',
                 'loc_x',
                 'accuracy',
                 'altitude',
                 'bearing',
                 'speed'),
  sms.incoming = c(names_prefix,
                   'number',
                   'time',
                   'text_length',
                   'text_words',
                   'text_average_word_length',
                   'text_letters',
                   'text_numbers',
                   'text_puncts',
                   'text_whites',
                   'is_email',
                   'is_status_report',
                   'is_replace',
                   'is_mwi'),
  sms.outgoing = c(names_prefix,
                   'number',
                   'time',
                   'text_length',
                   'text_words',
                   'text_average_word_length',
                   'text_letters',
                   'text_numbers',
                   'text_puncts',
                   'text_whites'),
  user.prefs.pause = names_prefix,
  device.battery.level = c(names_prefix,
                           'level',
                           'max_level',
                           'plugged',
                           'status')
)